[project]
name = "ch06-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beanie>=1.29.0",
    "fastapi>=0.115.12",
    "pydantic-settings>=2.8.1",
    "pydantic[email]>=2.11.1",
    "uvicorn>=0.34.0",
]
